version: '3.8'

services:
    db:
        container_name: db
        image: mongo
        ports:
            - "27017:27017"  
        volumes:
            - ./.data:/data/db
    api:
        container_name: api
        build: 
            dockerfile: Dockerfile
            context: "./server"
        ports :
            - "3000:3000"
        volumes:
            - /app/node_modules
            - ./server:/app
    client:
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        build:
            dockerfile: Dockerfile
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
