version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    networks:
      - loop-app-net
    volumes:
      - mongo_db:/data/db

  server:
    build: ./server
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      CONNECTION_STRING: 'mongodb://mongo_db:27017/test'
      JWT_KEY: Vdz7>K@W!5}pknh
      JWT_ACCESS_TOKEN: Vdz7>K@W!5}pknh
    networks:
      - loop-app-net
    depends_on: [mongo_db]

  client:
    build: ./client
    stdin_open: true
    ports:
      - '3000:3000'
    networks:
      - loop-app-net

networks:
  loop-app-net:
    driver: bridge

volumes:
  mongo_db:
    driver: local
