version: '3.8'

services:
  backend:
    build:
      context: ""
      dockerfile: Dockerfile
    ports:
    - 3000:3000
    - 5000:5000
    depends_on:
      - db
    links:
      - db

  db:
    image: mongo
    restart: always
    ports:
    - 8081:8081

#  frontend:
#    build:
#      context: .
#      dockerfile: client/Dockerfile
#    ports:
#      - 3000:3000
#    depends_on:
#      - backend
